Screen and producer
Joris-debug/code_camp-idle_game pull request #6
Opened 2024-12-04 09:02 UTC by alexkhr22

The Main, Inventory and Scoreboard screens have been implemented as well as provisional producers and a worker.

2024-12-04 11:10 UTC, 44616E69656C commented on Idle_Game/app/build.gradle.kts
Entferne bitte die deps für fragments

2024-12-04 11:23 UTC, 44616E69656C commented on Idle_Game/app/src/main/res/drawable/ic_inventory.xml
wird nicht benutzt?

2024-12-04 11:24 UTC, 44616E69656C commented on Idle_Game/app/src/main/res/menu/bottom_nav_menu.xml
ist in NavHost umbesetzt

2024-12-04 11:25 UTC, 44616E69656C commented on Idle_Game/app/src/main/res/values/themes.xml
wird nicht verwendet?

2024-12-04 11:26 UTC, 44616E69656C requested changes
Bitte überprüfe und ggf. entferne die xml Dateinen in [Idle_Game/app/src/main/res/](Idle_Game/app/src/main/res/menu/)

2024-12-04 12:39 UTC, alexkhr22 commented on Idle_Game/app/src/main/res/values/themes.xml
Wird im Manifest verwendet

2024-12-04 12:40 UTC, alexkhr22 commented on Idle_Game/app/src/main/res/menu/bottom_nav_menu.xml
Ist entfernt

2024-12-04 12:41 UTC, alexkhr22 commented on Idle_Game/app/src/main/res/drawable/ic_inventory.xml
Wurde drin gelassen als Platzhalter. Ist entfernt

2024-12-04 12:41 UTC, alexkhr22 commented on Idle_Game/app/build.gradle.kts
Ist entfernt

2024-12-05 07:52 UTC, Joris-debug requested changes
Ändere nicht die Database version, wenn du einen Fehler bekommst musst du nur die App einmal deinstallieren, dann ist der Fehler behoben

2024-12-05 14:36 UTC, 44616E69656C commented on Idle_Game/app/src/main/java/com/example/idle_game/MainActivity.kt
> +class MainActivity : AppCompatActivity() {
Da fragments nicht mehr verwendet werden sollte ComponentActivity ausreichen

2024-12-05 14:37 UTC, 44616E69656C commented on Idle_Game/app/build.gradle.kts
> +    implementation("androidx.appcompat:appcompat:1.7.0")
Siehe MainAktivity

2024-12-05 16:11 UTC, 44616E69656C commented on Idle_Game/app/src/main/java/com/example/idle_game/ui/navigation/NavigationGraph.kt
> -        NavigationBarItem(
Navigation zu den anderen Views können drin bleiben

2024-12-05 23:34 UTC, closed without merging